# @formatter:off // TODO: Do not remove this line to preserve the code style -----------------------
[versions]
# --------------------------------------------------------------------------------------------------
agp                          = "8.13.2"
kotlin                       = "2.2.21"
# --------------------------------------------------------------------------------------------------
junit                        = "4.13.2"
test-junit-ext               = "1.3.0"
test-espresso-core           = "3.7.0"
# --------------------------------------------------------------------------------------------------
kotlinx-coroutines           = "1.10.2"
kotlinx-serialization        = "1.9.0"
kotlinx-immutable            = "0.4.0"
# --------------------------------------------------------------------------------------------------
androidx-core-ktx            = "1.17.0"
androidx-lifecycle           = "2.10.0"
# --------------------------------------------------------------------------------------------------
androidx-compose-runtime     = "1.10.0"
# --------------------------------------------------------------------------------------------------
koin-core                    = "4.1.1"
# --------------------------------------------------------------------------------------------------
appcompat = "1.7.1"
activity = "1.12.2"

[libraries]
# Androidx
androidx-core-ktx  = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-activity  = { group = "androidx.activity", name = "activity", version.ref = "activity" }
# --------------------------------------------------------------------------------------------------
# Lifecycle
androidx-lifecycle-runtime-ktx   = { group = "androidx.lifecycle" , name = "lifecycle-runtime-ktx"   , version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle" , name = "lifecycle-viewmodel-ktx" , version.ref = "androidx-lifecycle" }
# --------------------------------------------------------------------------------------------------
# Compose
androidx-compose-runtime = { group = "androidx.compose.runtime" , name = "runtime" , version.ref = "androidx-compose-runtime" }
# --------------------------------------------------------------------------------------------------
# Koin
koin-core = { group = "io.insert-koin" , name = "koin-core" , version.ref = "koin-core" }
# --------------------------------------------------------------------------------------------------
# Jetbrains
jetbrains-kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android"    , version.ref = "kotlinx-coroutines"    }
jetbrains-kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core"    , version.ref = "kotlinx-serialization" }
jetbrains-kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json"    , version.ref = "kotlinx-serialization" }
jetbrains-kotlinx-immutable          = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable" , version.ref = "kotlinx-immutable"     }
# --------------------------------------------------------------------------------------------------
# Test
junit                  = { group = "junit"                  , name = "junit"         , version.ref = "junit"              }
androidx-junit         = { group = "androidx.test.ext"      , name = "junit"         , version.ref = "test-junit-ext"     }
androidx-espresso-core = { group = "androidx.test.espresso" , name = "espresso-core" , version.ref = "test-espresso-core" }
# --------------------------------------------------------------------------------------------------

[plugins]
# Android
android-application = { id = "com.android.application" , version.ref = "agp" }
android-library     = { id = "com.android.library"     , version.ref = "agp" }
# Jetbrains
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android" , version.ref = "kotlin" }
# Maven
maven-publish = { id = "maven-publish" }