# @formatter:off // TODO: Do not remove this line to preserve the code style -----------------------
[versions]
# Gradle Plugin ------------------------------------------------------------------------------------
agp                      = "9.0.0"
kotlin                   = "2.2.21"
ktlint                   = "14.0.1"
plugin-publish           = "2.0.0"
# Androidx -----------------------------------------------------------------------------------------
androidx-core-ktx        = "1.17.0"
androidx-appcompat       = "1.7.1"
androidx-activity        = "1.12.2"
androidx-fragment        = "1.8.9"
androidx-recyclerview    = "1.4.0"
androidx-annotation-jvm  = "1.9.1"
androidx-preferences     = "1.2.0"
androidx-crypto          = "1.1.0"
# Lifecycle ----------------------------------------------------------------------------------------
androidx-lifecycle       = "2.10.0"
# Compose ------------------------------------------------------------------------------------------
androidx-compose-runtime = "1.10.0"
# Jetbrains ----------------------------------------------------------------------------------------
kotlinx-coroutines       = "1.10.2"
kotlinx-serialization    = "1.9.0"
kotlinx-collections      = "0.4.0"
# Test ---------------------------------------------------------------------------------------------
junit                    = "4.13.2"
test-junit-ext           = "1.3.0"
test-espresso-core       = "3.7.0"

[libraries]
# Android ------------------------------------------------------------------------------------------
android-build-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
# Androidx -----------------------------------------------------------------------------------------------------------------------------
androidx-core           = { group = "androidx.core"         , name = "core-ktx"              , version.ref = "androidx-core-ktx"       }
androidx-activity       = { group = "androidx.activity"     , name = "activity-ktx"          , version.ref = "androidx-activity"       }
androidx-fragment       = { group = "androidx.fragment"     , name = "fragment-ktx"          , version.ref = "androidx-fragment"       }
androidx-appcompat      = { group = "androidx.appcompat"    , name = "appcompat"             , version.ref = "androidx-appcompat"      }
androidx-recyclerview   = { group = "androidx.recyclerview" , name = "recyclerview"          , version.ref = "androidx-recyclerview"   }
androidx-annotation-jvm = { group = "androidx.annotation"   , name = "annotation-jvm"        , version.ref = "androidx-annotation-jvm" }
androidx-datastore      = { group = "androidx.datastore"    , name = "datastore-preferences" , version.ref = "androidx-preferences"    }
androidx-crypto         = { group = "androidx.security"     , name = "security-crypto"       , version.ref = "androidx-crypto"         }
# Lifecycle -------------------------------------------------------------------------------------------------------------------------------
androidx-lifecycle-runtime-ktx   = { group = "androidx.lifecycle" , name = "lifecycle-runtime-ktx"   , version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle" , name = "lifecycle-viewmodel-ktx" , version.ref = "androidx-lifecycle" }
# Compose ---------------------------------------------------------------------------------------------------------------------
androidx-compose-runtime = { group = "androidx.compose.runtime" , name = "runtime" , version.ref = "androidx-compose-runtime" }
# Jetbrains ----------------------------------------------------------------------------------------------------------------------------------------
jetbrains-kotlinx-coroutines-android    = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android"    , version.ref = "kotlinx-coroutines"    }
jetbrains-kotlinx-serialization-core    = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core"    , version.ref = "kotlinx-serialization" }
jetbrains-kotlinx-serialization-json    = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json"    , version.ref = "kotlinx-serialization" }
jetbrains-kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable" , version.ref = "kotlinx-collections"   }
# Test --------------------------------------------------------------------------------------------------------------------
junit                  = { group = "junit"                  , name = "junit"         , version.ref = "junit"              }
androidx-junit         = { group = "androidx.test.ext"      , name = "junit"         , version.ref = "test-junit-ext"     }
androidx-espresso-core = { group = "androidx.test.espresso" , name = "espresso-core" , version.ref = "test-espresso-core" }

[plugins]
# Android ------------------------------------------------------------------------------------------
android-application = { id = "com.android.application" , version.ref = "agp" }
android-library     = { id = "com.android.library"     , version.ref = "agp" }
# Jetbrains --------------------------------------------------------------------------------------------------
jetbrains-kotlin-jvm           = { id = "org.jetbrains.kotlin.jvm"                                           }
jetbrains-kotlin-kapt          = { id = "org.jetbrains.kotlin.kapt"                                          }
jetbrains-kotlin-android       = { id = "org.jetbrains.kotlin.android"              , version.ref = "kotlin" }
jetbrains-kotlin-compose       = { id = "org.jetbrains.kotlin.plugin.compose"       , version.ref = "kotlin" }
jetbrains-kotlin-parcelize     = { id = "org.jetbrains.kotlin.plugin.parcelize"     , version.ref = "kotlin" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization" , version.ref = "kotlin" }
# Java -------------------------------------------------------------------------------------------------------
java-library  = { id = "java-library" }
java-platform = { id = "java-platform" }
# Maven --------------------------------------------------------------------------------------------
maven-publish = { id = "maven-publish" }
# Gradle -------------------------------------------------------------------------------------------
gradle-publish = { id = "com.gradle.plugin-publish" , version.ref = "plugin-publish" }
# KtLint -------------------------------------------------------------------------------------------
ktlint = { id = "org.jlleitschuh.gradle.ktlint" , version.ref = "ktlint" }
# BuilLogic ----------------------------------------------------------------------------------------
andromeda-publishing = { id = "ir.farsroidx.andromeda-publishing" }